### ISSUE TITLE
accept `solid:instance` as containerUrl in soukai solid models

### ISSUE THREAD

**Issue by the-reza-soltani** [NoelDeMartin/soukai-solid#17]
it seems soukai models can only accept `solid:instanceContainer` as containerUrls, and not `solid:instance`

**Comment by NoelDeMartin** [comment]
I've looked at the code and it seems like `solid:instance` was already declared on the `SolidTypeRegistration` model, so I'm not sure what you meant.

But I've gone over all the type index utilities, and some things were missing to read or register instances, so maybe that's what you wanted. I released a new version `0.5.2` with the new helpers and I wrote a couple of tests to show how you can use them: [interoperability.test.ts](https://github.com/NoelDeMartin/soukai-solid/blob/main/src/tests/interoperability.test.ts).

I think that should be enough to do anything you want with type indexes, but let me know if I'm missing something and we can reopen the issue.

**Comment by itsrezasoltani** [comment]
you have couple of changes in `0.5.1-next.17ce9fccdbfa3d99bd1718e9aaf169cea189ee8a`
are those also shipped with this version?
things like:
SolidContainer.fromTypeindex gives you SolidContainer[] and not SolidContainer

**Comment by itsrezasoltani** [comment]
yes, it seems those are also shipped 
thanks

**Comment by itsrezasoltani** [comment]
maybe it worth announcing a breaking change in this version just because of this
I'm not sure if it can count as a patch version

**Comment by itsrezasoltani** [comment]
Could you please reopen this issue?
The main problem still exists:

Think you have a document in `https://solid-dm.solidcommunity.net/bookmarks/index.ttl`

With current implementations (as far as I know) you can only get the bookmarks with
`await Bookmark.from("https://solid-dm.solidcommunity.net/bookmarks/").all()` container with file per document
and not with:
`await Bookmark.from("https://solid-dm.solidcommunity.net/bookmarks/index.tts").all()` instance with one file for all documents

this is the way Inrupt clients works for example


hint: models can only accept container URLs (ending with traling slashes) and not instanceUrls

**Comment by itsrezasoltani** [comment]
I already solved the thing you tested

Getting instance Urls from TypeIndex`

```typescript
export const fromTypeIndex = async (
    typeIndexUrl: string,
    childrenModelClass: typeof SolidModel
) => {
    const engine = getEngine();

    const fetch = engine instanceof SolidEngine ? engine.getFetch() : undefined;

    const containerPromise = findContainerRegistrations(typeIndexUrl, childrenModelClass.rdfsClasses, fetch);

    const instancePromise = findInstanceRegistrations(typeIndexUrl, childrenModelClass.rdfsClasses, fetch);

    const allPromise = Promise.all([containerPromise, instancePromise]);

    try {
        const [containers, instances] = await allPromise;

        const result = [
            ...containers.map(url => SolidContainer.newInstance({ url }, true)),
            ...instances.map(url => SolidContainer.newInstance({ url }, true))
        ]

        return result

    } catch (error) {
        console.log("🚀 ~ file: utils.ts:389 ~ error:", error)
    }
};
```

**Comment by NoelDeMartin** [comment]
> maybe it worth announcing a breaking change in this version just because of this

Yes, you're completely right, that should have been a breaking change. It totally skipped my mind, sorry about that >.<.

I documented it in [the changelog](https://github.com/NoelDeMartin/soukai-solid/blob/main/CHANGELOG.md), but I won't release a new "major version" (until 1.0.0, I consider all the 0.X majors) because I try to keep the same versions for core `soukai` as well. So if I release 0.6.0 I should do the same for the core library, and I don't think it's worth the trouble.

Hopefully I'll be more careful in the future, thanks for mentioning it.

> models can only accept container URLs (ending with traling slashes) and not instanceUrls

Ok, I think I see where's the problem now. I don't have a background working with RDF, that's why many of the things that would be obvious for anyone experienced with RDF, are new to me.

In this case, I was confused because I don't usually consider this use-case of having multiple models in a single document. I always store a single model per document, or at least there is always a main one and the others are defined through relationships (for example, I use a single document for each `schema:Movie` and there can be `schema:WatchAction` models in the document as well).

But I'm aware there are other ways of modeling data in the wild. The design goal of Soukai is to work with this mental model though, because the type of apps I've built so far don't need to interact with pre-existing data. But I know the world of the Semantic Web is very flexible. And I'm sorry to say that I'm not sure if Soukai is the best library to handle that flexibility :/. The decision to use the Active Record pattern comes with some trade-offs. Technically, you should still be able to do anything, but some things won't be so straightforward and maybe you'd be better off not using Active Record but working with the semantic data directly.

Having said that, though, there is a way to do what you want! So maybe you can disregard what I just said, but I still think it's important that you knew. I've documented my thoughts on this in a new section of the README so that you understand what I mean: [Data modeling and retrieval strategies](https://github.com/NoelDeMartin/soukai-solid#data-modeling-and-retrieval-strategies). But the TLDR is that you can already retrieve models from documents rather than containers doing the following:

```js
const bookmarks = await Bookmark.all({
    $in: ['https://solid-dm.solidcommunity.net/bookmarks/index.ttl'],
});

```

And the reason why `await Bookmark.from("https://solid-dm.solidcommunity.net/bookmarks/index.ttl").all()` doesn't work is that `https://solid-dm.solidcommunity.net/bookmarks/index.ttl` is not a container url. In Soukai, collections are containers. So if you want to retrieve models from anything other than a container, you cannot use the `from` method (which just sets the collection under the hood).

Hopefully that works for you. I'm reopening this issue in case something's still not clear or I need to change something. Let me know what you think.

**Comment by NoelDeMartin** [comment]
I'm closing this in favour of NoelDeMartin/soukai#6, let me know if there is something else that's not covered there.
